### ISSUE TITLE
Run on CPU

### ISSUE THREAD

**Issue by n12iB** [IDEA-Research/detrex#105]
Hi,
Is it possible to train the model only using a CPU? I tried changing projects/dab_detr/configs/models/dab_detr_r50.py file so that device is cpu, but it seems to still try to use GPUs.

**Comment by rentainhe** [comment]
> Hi, Is it possible to train the model only using a CPU? I tried changing projects/dab_detr/configs/models/dab_detr_r50.py file so that device is cpu, but it seems to still try to use GPUs.

Apologies for the misunderstandings for the lack of clarifications in our documentation and config files, if you want to train model on CPU, you need to both update the `train` config and `model` config as following:

```python
# your config file

train.device = "cpu"
model.device = train.device
```

**Comment by rentainhe** [comment]
We've already rebuild the config files to make it more clear in this PR: https://github.com/IDEA-Research/detrex/pull/107
@n12iB

**Comment by n12iB** [comment]
@rentainhe thank you

**Comment by rentainhe** [comment]
As there is no more activity, I am closing the issue~ Feel free to reopen it if necessary. Or you can leave a new issue if you meet some other problems.
