### ISSUE TITLE
Fine-tune on custom dataset

### ISSUE THREAD

**Issue by Ashores** [IDEA-Research/detrex#106]
Hello, I tried to train a custom dataset on detrex, but an RTX-3090 still reports out of memory. The same device is trained enough in the DINO source code, I guess this is because of the extra memory consumption brought by the Detrex framework, or some of my parameter settings?

**Comment by Ashores** [comment]
Thanks for your quick reply.
Sorry I didn't notice this parameter before, I thought it was controlled by num-workers. Now that it has been modified, I suggest that batch-size can be mapped to the config of each model, which is a bit hard to find in this location.

**Comment by rentainhe** [comment]
> Thanks for your quick reply. Sorry I didn't notice this parameter before, I thought it was controlled by num-workers. Now that it has been modified, I suggest that batch-size can be mapped to the config of each model, which is a bit hard to find in this location.

Thanks a lot for your advice, we will update all of the configs in detrex projects later~, it's our fault that we did not make a clear clarifications about the commonly used settings in config files.

**Comment by Ashores** [comment]
Thank you very much for your work
