### ISSUE TITLE
Add a basic usage notebook for inference on custom images

### ISSUE THREAD

**Issue by Fariborzzz** [IDEA-Research/detrex#113]
Thank you for the nice work. 
In original DINO repo, there is a very handy inference notebook using custom data. It would be nice to add it to this repo as well.

Cheers,

**Comment by rentainhe** [comment]
> Thank you for the nice work. In original DINO repo, there is a very handy inference notebook using custom data. It would be nice to add it to this repo as well.
> 
> Cheers,

Thank you for your encouragement and nice advice, we will add a demo like [detectron2/demo](https://github.com/facebookresearch/detectron2/tree/main/demo) for users to visualize the detection results of their specific input image and video!

**Comment by alrightkami** [comment]
I would also find it very helpful to have an inference notebook, thanks in advance!

**Comment by rentainhe** [comment]
I've already create a new PR for visualizing on customized input image, you can refer to this https://github.com/IDEA-Research/detrex/pull/119 for more details, and this demo will be merged into main branch after more testing.

@alrightkami @Fariborzzz

**Comment by alrightkami** [comment]
@rentainhe Thank you so much! The inference script is finally working :)

**Comment by Fariborzzz** [comment]
Thank @rentainhe and the team! hope I can contribute to your great work later !

**Comment by rentainhe** [comment]
> @rentainhe Thank you so much! The inference script is finally working :)

You're welcome~ so much sorry for not replying to your previous question in time @alrightkami

**Comment by rentainhe** [comment]
> Thank @rentainhe and the team! hope I can contribute to your great work later !

You're welcome, We appreciate all kinds of contributions to further improve detrex！

**Comment by rentainhe** [comment]
I am closing the issue~ Feel free to reopen it if necessary. Or you can leave a new issue if you meet some other problems.
