### ISSUE TITLE
How to visualize the reference points of DNDeformableDETR?

### ISSUE THREAD

**Issue by Mr-Bigworth** [IDEA-Research/detrex#121]
About the reference points of Deformable DETR and DNDeformableDETR, I wonder how to plot them in the figure. Thanks!

**Comment by FengLi-ust** [comment]
You need to get the reference points of the layer you want to plot, then you can use scatter or other functions to plot it.

**Comment by Mr-Bigworth** [comment]
> You need to get the reference points of the layer you want to plot, then you can use scatter or other functions to plot it.

Thanks, I have solved it.
