### ISSUE TITLE
SwinV2 support

### ISSUE THREAD

**Issue by becauseofAI** [IDEA-Research/detrex#122]
Is SwinV2 in your plan? Will you release DINO-SwinV2-L and DINO-SwinV2-G model?

**Comment by rentainhe** [comment]
> Is SwinV2 in your plan? Will you release DINO-SwinV2-L and DINO-SwinV2-G model?

Yes, it's in our plan, we will support SwinV2 in the future release. And we can only release `DINO-SwinV2-L` baselines, because `SwinV2-G` is not released in the official repo.

**Comment by rentainhe** [comment]
We will implement Swin-V2-DINO in this PR: https://github.com/IDEA-Research/detrex/pull/152, stay tuned! @becauseofAI 

And I'm closing this issue~ Feel free to reopen it if needed~
