### ISSUE TITLE
HDETR'checkpoint is not found

### ISSUE THREAD

**Issue by hotcore** [IDEA-Research/detrex#129]
man i just click the model in hdetr to download checkpoint but is not found, is something wrong?

**Comment by hotcore** [comment]
man i just click the model in hdetr to download checkpoint but is not found, is something wrong?

**Comment by rentainhe** [comment]
> _No description provided._

Sry, we've forgot to update the links, we will update it later, all the H-DETR checkpoint can be found in https://github.com/IDEA-Research/detrex-storage/releases

**Comment by hotcore** [comment]
> > _No description provided._
> 
> Sry, we've forgot to update the links, we will update it later, all the H-DETR checkpoint can be found in https://github.com/IDEA-Research/detrex-storage/releases @hotcore

ok, i really appreciate that, excellent work man！

**Comment by rentainhe** [comment]
> > > _No description provided._
> > 
> > 
> > Sry, we've forgot to update the links, we will update it later, all the H-DETR checkpoint can be found in https://github.com/IDEA-Research/detrex-storage/releases @hotcore
> 
> ok, i really appreciate that, excellent work man！

Thanks a lot for your encouragement~
