### ISSUE TITLE
About DINO change on 0.2.0

### ISSUE THREAD

**Issue by WesleyZCheng** [IDEA-Research/detrex#130]
Hi, it's glad that you and your team release the new version about 0.2.0. 
I found that the major update for this version is in DAB-DETR, which modified some configurations. I read in README that the new version will be in Rebuild cleaner config files for projects. Do you mean DABDETR? I am a user of DINO, whether the update of DINO is the update of the training weight of `DINO-r50-12ep`, cause it has a better training effect. The main model configuration files were not adjusted.

**Comment by rentainhe** [comment]
> Hi, it's glad that you and your team release the new version about 0.2.0. I found that the major update for this version is in DAB-DETR, which modified some configurations. I read in README that the new version will be in Rebuild cleaner config files for projects. Do you mean DABDETR? I am a user of DINO, whether the update of DINO is the update of the training weight of `DINO-r50-12ep`, cause it has a better training effect. The main model configuration files were not adjusted.

We've build a more clear and cleaner config files for the users cuz there are some hyper-params not clear before as mentioned in this issue https://github.com/IDEA-Research/detrex/issues/105

**Comment by WesleyZCheng** [comment]
> > Hi, it's glad that you and your team release the new version about 0.2.0. I found that the major update for this version is in DAB-DETR, which modified some configurations. I read in README that the new version will be in Rebuild cleaner config files for projects. Do you mean DABDETR? I am a user of DINO, whether the update of DINO is the update of the training weight of `DINO-r50-12ep`, cause it has a better training effect. The main model configuration files were not adjusted.
> 
> We've build a more clear and cleaner config files for the users cuz there are some hyper-params not clear before as mentioned in this issue #105 @WesleyZCheng

@rentainhe thanks for the reply, and it's much clearer by now.

**Comment by rentainhe** [comment]
> > > Hi, it's glad that you and your team release the new version about 0.2.0. I found that the major update for this version is in DAB-DETR, which modified some configurations. I read in README that the new version will be in Rebuild cleaner config files for projects. Do you mean DABDETR? I am a user of DINO, whether the update of DINO is the update of the training weight of `DINO-r50-12ep`, cause it has a better training effect. The main model configuration files were not adjusted.
> > 
> > 
> > We've build a more clear and cleaner config files for the users cuz there are some hyper-params not clear before as mentioned in this issue #105 @WesleyZCheng
> 
> @rentainhe thanks for the reply, and it's much clearer by now.

Thanks a lot~ And I am closing the issue~ Feel free to reopen it if necessary.
