### ISSUE TITLE
Support of multi-machine training

### ISSUE THREAD

**Issue by Artificial-Inability** [IDEA-Research/detrex#133]
Does detrex support multi-machine training(not single machine multiple GPU)? If not , are you planning to support it? Thanks!

**Comment by rentainhe** [comment]
> Does detrex support multi-machine training(not single machine multiple GPU)? If not , are you planning to support it? Thanks!

We directly build detrex based on detectron2, and detectron2 has already supported `multi-node` and `multi-gpus` training I think, but we did not test it in detrex now, we will test it later, maybe you can also refer to detectron2 [lazyconfig_train_net](https://github.com/facebookresearch/detectron2/blob/main/tools/lazyconfig_train_net.py#L122) for more details, and after our testing, we will provide a tutorial about this

I thinks more details can be found in their [launch](https://github.com/facebookresearch/detectron2/blob/96c752ce821a3340e27edd51c28a00665dd32a30/detectron2/engine/launch.py#L1) wrapper for multi-node and multi-gpus training

**Comment by Artificial-Inability** [comment]
Thanks, I will try to figure it out by myself first and I'm looking forward to your tutorial and test performance report.

**Comment by rentainhe** [comment]
> Thanks, I will try to figure it out by myself first and I'm looking forward to your tutorial and test performance report.

Thanks, we will try to build a better docs for users~ thanks for your nice issue @Artificial-Inability
