### ISSUE TITLE
typo typo 

### ISSUE THREAD

**Issue by CiaoHe** [IDEA-Research/detrex#139]
https://github.com/IDEA-Research/detrex/blob/ac86bb573289f2b19dd674f935cce1cc6621656b/detrex/layers/denoising.py#L39
`new_lebels` -> `new_labels`
Enjoy!

**Comment by rentainhe** [comment]
> https://github.com/IDEA-Research/detrex/blob/ac86bb573289f2b19dd674f935cce1cc6621656b/detrex/layers/denoising.py#L39
> 
> 
> `new_lebels` -> `new_labels`
> Enjoy!

We will fix it in next PR~

**Comment by rentainhe** [comment]
Already fix in this PR: https://github.com/IDEA-Research/detrex/pull/152
