### ISSUE TITLE
DINO R50复现不到49.2的精度啊

### ISSUE THREAD

**Issue by yourlovedu** [IDEA-Research/detrex#142]
你们开源的dino的r50的config有问题啊。。如果用R50的pkl，应该是BGR模式，mean和std要相应的变化。。我修正了之后跑了12个ep，AP也只有48.3左右，没有达到你们报的49.2。又多跑了三四个ep，也就到48.7。我看了mm里面有人复现了dino的一个branch，试了一堆seed，ap也只是到48.9左右。。你们在训练时是用了什么骚操作吗？能不能把训练的log也分享一下啊

**Comment by yourlovedu** [comment]
这个cfg，修改了输入格式为BGR，mean和std也做了对应的修改：
https://github.com/IDEA-Research/detrex/blob/main/projects/dino/configs/dino_r50_4scale_12ep.py

**Comment by rentainhe** [comment]
> 你们开源的dino的r50的config有问题啊。。如果用R50的pkl，应该是BGR模式，mean和std要相应的变化。。我修正了之后跑了12个ep，AP也只有48.3左右，没有达到你们报的49.2。又多跑了三四个ep，也就到48.7。我看了mm里面有人复现了dino的一个branch，试了一堆seed，ap也只是到48.9左右。。你们在训练时是用了什么骚操作吗？能不能把训练的log也分享一下啊

we use torchvision pretrained model, and the input format is RGB, please check the whole config for the details

**Comment by rentainhe** [comment]
As there is no more activity, I am closing the issue, feel free to reopen it if necessary.
