### ISSUE TITLE
About the number of params in detrex

### ISSUE THREAD

**Issue by WesleyZCheng** [IDEA-Research/detrex#148]
Hi, there, I'm coming back. For now, maybe I want to find out where  I can find the total parameters of the entire model in detrex.

I'm using the dino. In the original repo, I can find it from the `info.txt` file which outputs the log Information, the num of parameters will show below the code block.
```
[08/19 12:39:32.347]: number of params:46397196
[08/19 12:39:32.349]: params:
```
in detrex, I can't find it from` log.txt`, so where can I find this or where can I calculate this number from the file which end with `py` in detrex. 

Looking forward for your reply.

**Comment by WesleyZCheng** [comment]
thanks a lot!

**Comment by rentainhe** [comment]
> thanks a lot!

You're welcome~ : ）
