### ISSUE TITLE
Cuda out of memory error when training mask-Dino

### ISSUE THREAD

**Issue by Asafgendler** [IDEA-Research/detrex#158]
Hello,

I am trying to train your newly uploaded mask-Dino on a new dataset (still in the COCO format).

I am using 8 Tesla V100-SXM2-16GB GPUs, and getting a cuda out of memory error message, even when setting the batch size to 1 for each GPU. (I am training using the detrex training script).

Importantly, the code crashes only after few training iterations and not immediately.

Is this behavior predictable?  which hardware did you use to train the model?

Thanks,

![Screen Shot 2022-12-05 at 14 26 28](https://user-images.githubusercontent.com/62475971/205637188-93d0b363-7e59-47aa-b0d8-fe8777a2dff3.png)

**Comment by HaoZhang534** [comment]
Hi @Asafgendler, training with batch size=1 requires about 18G. You can try to use checkpointing or smaller model size. For example, you can reduce number of encoder/decoder layers or use fewer queries.

**Comment by HaoZhang534** [comment]
Hi @Asafgendler, training with batch size=1 requires about 18G. You can try to use checkpointing or a smaller model size. For example, you can reduce number of encoder/decoder layers or use fewer queries.

**Comment by Asafgendler** [comment]
Thanks
