### ISSUE TITLE
Potential problem of GroupConditionalSelfAttention

### ISSUE THREAD

**Issue by xyupeng** [IDEA-Research/detrex#163]
Hi there,

I see the implementation of `GroupConditionalSelfAttention` and find that it may have some problems.
https://github.com/IDEA-Research/detrex/blob/75318d139157ea2dbf0b3100a3dc3623d9740878/projects/group_detr/modeling/attention.py#L143-L158
In line 154-158, qkv are reshaped to N=num_groups * num_queries_per_group. In this way, all queries in all groups interact with each other, rather than interacting within each group. Is this implementation a potential mistake? Or I misunderstand something?

**Comment by SlongLiu** [comment]
Thanks for your issues. 

Thanks to the suggestions of @charlesCXK (the author of group-detr), we find it is a bug in our implementations. We will fix it in our next version.

**Comment by rentainhe** [comment]
I'm closing this issue~ we will try to correct the potential bug after Group-DETR full release, and feel free to reopen this issue if needed~
