### ISSUE TITLE
Would DINO work with ConvNext?

### ISSUE THREAD

**Issue by momopusheen** [IDEA-Research/detrex#170]
Hi there,
I noticed that in detrex, there's ConvNext.py under detrex/modeling/backbone. However, in project/dino, there aren't any configs with ConvNext. I wonder if we can use ConvNext as backbone in place of res50 or swin transformer? If possible, would it perform comparable with swin?
Thanks for your consideration!

**Comment by HaoZhang534** [comment]
@momopusheen We do not support Convnext temporally. According to our experience, ConvNext does not outperform Swin.

**Comment by rentainhe** [comment]
As there is no more activity, I am closing the issue~ Feel free to reopen it if necessary. Or you can leave a new issue if you meet some other problems.
