### ISSUE TITLE
"RuntimeError: selected index k out of range" in h_deformable_detr

### ISSUE THREAD

**Issue by KappyDays** [IDEA-Research/detrex#180]
Hi, thank you for providing a nice project

I'm using "projects > h_deformable_detr > configs > h_deformable_detr_swin_large_two_stage_12ep.py" to train my custom dataset(Object Detection, Using Bbox-COCO Label).

When i entered this command,

`python tools/train_net.py --config-file projects/h_deformable_detr/configs/h_deformable_detr_swin_large_two_stage_12ep.py`

The RuntimeError is Raised.
![image](https://user-images.githubusercontent.com/47882543/209744878-3529c060-8cf7-4460-a2aa-9ce590372333.png)

To solve this problem, I printed out the shape of enc_outputs_class and the value of the topk variable.
![image](https://user-images.githubusercontent.com/47882543/209746152-7623c3f8-70ea-4cce-b022-a1580e711b96.png)

And I checked that the value of enc_outputs_class is less than the value of topk. (1781 < 1800)

But I don't know how to fix it.

Besides, the part I modified in another file is the value of the num_classes variable in "projects > h_deformable_detr > configs > models > h_deformable_detr_r50.py"

I modified num_classes=1 because my custom dataset only has 1 class.

Thanks for reading and I hope this problem gets resolved.

**Comment by FengLi-ust** [comment]
You need to use less number of queries or groups, i.e., 1500 in total. You can also pad the queries to 1800 with randomly initialized queries when the shape of enc_outputs_class and the value of the topk variable.

**Comment by rentainhe** [comment]
As there is no more activity, I am closing the issue, feel free to reopen it if necessary~

**Comment by nhw649** [comment]
> You need to use less number of queries or groups, i.e., 1500 in total. You can also pad the queries to 1800 with randomly initialized queries when the shape of enc_outputs_class and the value of the topk variable.

Hello, I have the same problem. I want to know whether to use all zero initialization or random initialization, is there a specific implementation of the code?
