### ISSUE TITLE
Training DINO

### ISSUE THREAD

**Issue by wishforgood** [IDEA-Research/detrex#181]
What is the correct way for training a dino model? 

I tried `python tools/train_net.py     --config-file projects/dino/configs/dino_r50_4scale_12ep.py` like instructed in the doc, but got an error says `TypeError: get_default_optimizer_params() got an unexpected keyword argument 'lr_factor_func'`. I checked the code and found that `dino_r50_4scale_12ep.py` is really using `get_default_optimizer_params()`, which has not such an input.

**Comment by rentainhe** [comment]
> What is the correct way for training a dino model?
> 
> I tried `python tools/train_net.py --config-file projects/dino/configs/dino_r50_4scale_12ep.py` like instructed in the doc, but got an error says `TypeError: get_default_optimizer_params() got an unexpected keyword argument 'lr_factor_func'`. I checked the code and found that `dino_r50_4scale_12ep.py` is really using `get_default_optimizer_params()`, which has not such an input.

It seems like your detectron2 is not the correct version, you should install d2 follow our official installation guide: https://detrex.readthedocs.io/en/latest/tutorials/Installation.html

which we keep the version of detectron2 fixed using github submodule @wishforgood

**Comment by wishforgood** [comment]
> 

Sorry, I'm not able to install d2 following your guide, after installing that way, I run random codes and got an error like this

![微信图片_20221231235008](https://user-images.githubusercontent.com/9963412/210148885-8c731b90-bae0-4100-b8b5-ec96d8777b68.jpg)

It seems like that the c++ part failed to be compiled.

So I tried to install a fixed pre-compiled version of d2, which I thought was the newest one: `https://github.com/facebookresearch/detectron2/releases/tag/v0.6`

**Comment by rentainhe** [comment]
> > 
> 
> Sorry, I'm not able to install d2 following your guide, after installing that way, I run random codes and got an error like this
> 
> ![微信图片_20221231235008](https://user-images.githubusercontent.com/9963412/210148885-8c731b90-bae0-4100-b8b5-ec96d8777b68.jpg)
> 
> It seems like that the c++ part failed to be compiled.
> 
> So I tried to install a fixed pre-compiled version of d2, which I thought was the newest one: `https://github.com/facebookresearch/detectron2/releases/tag/v0.6`

This is not the newest one, it's only the newest package~, maybe you should figure out how to install their latest code, our guide is one way

**Comment by wishforgood** [comment]
> > > 
> > 
> > 
> > Sorry, I'm not able to install d2 following your guide, after installing that way, I run random codes and got an error like this
> > ![微信图片_20221231235008](https://user-images.githubusercontent.com/9963412/210148885-8c731b90-bae0-4100-b8b5-ec96d8777b68.jpg)
> > It seems like that the c++ part failed to be compiled.
> > So I tried to install a fixed pre-compiled version of d2, which I thought was the newest one: `https://github.com/facebookresearch/detectron2/releases/tag/v0.6`
> 
> This is not the newest one, it's only the newest package~, maybe you should figure out how to install their latest code, our guide is one way

OK, I understand. I will try again to compile it someway.

**Comment by rentainhe** [comment]
> > > > 
> > > 
> > > 
> > > Sorry, I'm not able to install d2 following your guide, after installing that way, I run random codes and got an error like this
> > > ![微信图片_20221231235008](https://user-images.githubusercontent.com/9963412/210148885-8c731b90-bae0-4100-b8b5-ec96d8777b68.jpg)
> > > It seems like that the c++ part failed to be compiled.
> > > So I tried to install a fixed pre-compiled version of d2, which I thought was the newest one: `https://github.com/facebookresearch/detectron2/releases/tag/v0.6`
> > 
> > 
> > This is not the newest one, it's only the newest package~, maybe you should figure out how to install their latest code, our guide is one way
> 
> OK, I understand. I will try again to compile it someway.

the other way is that you can try to find the specific pull request and add the code into your own local package~

**Comment by wishforgood** [comment]
> 

No need to recompile? OK, that's a good news, thanks. I will try it.

**Comment by rentainhe** [comment]
> > 
> 
> No need to recompile? OK, that's a good news, thanks. I will try it.

Yes, it's just pytorch code, find the specific pr about adding `lr_factor_func`, and just add these code into your own local detectron2 package~
