### ISSUE TITLE
assert (boxes1[:, 2:] >= boxes1[:, :2]).all() training DAB-DETR

### ISSUE THREAD

**Issue by caopulan** [IDEA-Research/detrex#182]
I train DAB-DETR R50 with config ```projects/dab_detr/configs/dab_detr_r50_50ep.py``` and only change 
```lr_multiplier = get_config("common/coco_schedule.py").lr_multiplier_50ep``` to 
```lr_multiplier = get_config("common/coco_schedule.py").lr_multiplier_12ep``` to train 12epoch.
I use 4 TitanRTX(24G), but get ```assert (boxes1[:, 2:] >= boxes1[:, :2]).all()``` twice.

**Comment by HaoZhang534** [comment]
Hi, I think this might happen when you get nan in your output, but we have not met this during the training of DAB-DETR. Did you change anything else?

**Comment by caopulan** [comment]
> Hi, I think this might happen when you get nan in your output, but we have not met this during the training of DAB-DETR. Did you change anything else?

I also set ```train.max_iter = 90000``` without any changes else. I try again and set another random_seed (916), exp is running as for now (10000iterations). But performance is significantly weak. AP decreases from 0.00021 to 0.00019 at 5000 and 10000 iterations.

**Comment by caopulan** [comment]
I solved this problem by re-install detectron2 with the specified commit (717ab9f0aeca216a2f800e43d705766251ba3a55).
You can reproduce my issue by using ```python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'``` to install the newest d2. 
There may be some changes in d2 causing training non-convergence.
