### ISSUE TITLE
There is a lot of blank space

### ISSUE THREAD

**Issue by ma3252788** [IDEA-Research/detrex#184]
When I use detrex for training, I got a lot of blanks:

![image](https://user-images.githubusercontent.com/22229456/211230291-6596805e-0bfb-4e1b-8baf-85f2e417c37f.png)

**Comment by ma3252788** [comment]
I changed several servers, all of which are like this

**Comment by rentainhe** [comment]
> I changed several servers, all of which are like this

This is the logging info about `loading pretrained weights`, which will print the matched keys of your pretrained weights and models, I think it's a normal, all the unmatched key will be logged after printing this with green and purple colors

**Comment by ma3252788** [comment]
> > I changed several servers, all of which are like this
> 
> This is the logging info about `loading pretrained weights`, which will print the `matched keys` of your pretrained weights and models, I think it's a normal, all the unmatched keys will be logged after printing this with green and purple colors

I used the officially provided pre-trained models, as well as the COCO2017 dataset. There are very, very many of these empty lines, and since there are no automatic line breaks, I need to scroll with the mouse for a long time to see the beginning output content.

**Comment by rentainhe** [comment]
> > > I changed several servers, all of which are like this
> > 
> > 
> > This is the logging info about `loading pretrained weights`, which will print the `matched keys` of your pretrained weights and models, I think it's a normal, all the unmatched keys will be logged after printing this with green and purple colors
> 
> I used the officially provided pre-trained models, as well as the COCO2017 dataset. There are very, very many of these empty lines, and since there are no automatic line breaks, I need to scroll with the mouse for a long time to see the beginning output content.

we will take a look into it and try to improve the logging function

**Comment by ma3252788** [comment]
> > > > I changed several servers, all of which are like this
> > > 
> > > 
> > > This is the logging info about `loading pretrained weights`, which will print the `matched keys` of your pretrained weights and models, I think it's a normal, all the unmatched keys will be logged after printing this with green and purple colors
> > 
> > 
> > I used the officially provided pre-trained models, as well as the COCO2017 dataset. There are very, very many of these empty lines, and since there are no automatic line breaks, I need to scroll with the mouse for a long time to see the beginning output content.
> 
> we will take a look into it and try to improve the logging function

I just looked at log.txt and I noticed that in the output of checkpoint, there are a lot of spaces in each line and each line has 14501 characters, which I think is the main reason for showing a lot of empty lines in the terminal.

![image](https://user-images.githubusercontent.com/22229456/211896800-a767afaf-e8b8-424b-8b3f-7d9e96ef6bfb.png)

But this problem does not exist when outputting the network structure, I think it can be outputted according to the network structure.

![image](https://user-images.githubusercontent.com/22229456/211897488-9d92f4da-55f8-45b8-8797-0bda2c5c7d78.png)

**Comment by rentainhe** [comment]
> > > > > I changed several servers, all of which are like this
> > > > 
> > > > 
> > > > This is the logging info about `loading pretrained weights`, which will print the `matched keys` of your pretrained weights and models, I think it's a normal, all the unmatched keys will be logged after printing this with green and purple colors
> > > 
> > > 
> > > I used the officially provided pre-trained models, as well as the COCO2017 dataset. There are very, very many of these empty lines, and since there are no automatic line breaks, I need to scroll with the mouse for a long time to see the beginning output content.
> > 
> > 
> > we will take a look into it and try to improve the logging function
> 
> I just looked at log.txt and I noticed that in the output of checkpoint, there are a lot of spaces in each line and each line has 14501 characters, which I think is the main reason for showing a lot of empty lines in the terminal.
> 
> ![image](https://user-images.githubusercontent.com/22229456/211896800-a767afaf-e8b8-424b-8b3f-7d9e96ef6bfb.png)
> 
> But this problem does not exist when outputting the network structure, I think it can be outputted according to the network structure.
> 
> ![image](https://user-images.githubusercontent.com/22229456/211897488-9d92f4da-55f8-45b8-8797-0bda2c5c7d78.png)

Yes, in detectron2, If the names of two nodes are similar, they will be merged into one line in order to simplify the output. This may lead to too much text in a single line, making it unable to be completely displayed. It's a good way to just print the nodes' name and not merge them, but which may need to hack the `DetectionCheckpointer`

**Comment by YTEP-ZHI** [comment]
I had the same problem. When loading weights with unmatched keys, the output log is filled with **A LOT of blank spaces** among those keys. Is there any way to solve that problem? @rentainhe

**Comment by YTEP-ZHI** [comment]
![image](https://user-images.githubusercontent.com/48089846/217290333-938b4066-57c9-42b1-8a27-51c6b31aa9bb.png)

The unmatched keys in the logs are too difficult to read.

**Comment by rentainhe** [comment]
> ![image](https://user-images.githubusercontent.com/48089846/217290333-938b4066-57c9-42b1-8a27-51c6b31aa9bb.png)
> 
> The unmatched keys in the logs are too difficult to read.

We will take a look into this logging info recently,  the blanks means the matched keys actually, unmatched keys will be printed in other ways~

**Comment by YTEP-ZHI** [comment]
> > ![image](https://user-images.githubusercontent.com/48089846/217290333-938b4066-57c9-42b1-8a27-51c6b31aa9bb.png)
> > The unmatched keys in the logs are too difficult to read.
> 
> We will take a look into this logging info recently, the blanks means the matched keys actually, unmatched keys will be printed in other ways~

Thanks，hope this issue could be addressed soon.

**Comment by rentainhe** [comment]
We have already fixed this issue in this PR: https://github.com/IDEA-Research/detrex/pull/203, which will be merged into main recently

## Loading Checkpoint
![image](https://user-images.githubusercontent.com/48727989/217735754-3eb711c9-99a3-497e-a5dc-894299621f90.png)

There's no blank any more in this case `DINO-R50`

@ma3252788 @YTEP-ZHI

**Comment by YTEP-ZHI** [comment]
Thanks for your hard work.

**Comment by rentainhe** [comment]
I'm closing this issue, feel free to reopen it if needed~ @ma3252788 @YTEP-ZHI
