### ISSUE TITLE
How can I use a custom dataset for training?

### ISSUE THREAD

**Issue by ma3252788** [IDEA-Research/detrex#186]
How can I use a custom dataset for training?

I have made the data in COCO2017 format, but the number of classes and class names are different from COCO, which file should I change?

**Comment by rentainhe** [comment]
> How can I use a custom dataset for training?
> 
> I have made the data in COCO2017 format, but the number of classes and class names are different from COCO, which file should I change?

You can use this functions: [register_coco_instances](https://detectron2.readthedocs.io/en/latest/modules/data.html?highlight=register_coco#detectron2.data.datasets.register_coco_instances) to register your dataset in config file, and then update the dataset name

**Comment by rentainhe** [comment]
Here is an example:
```python
# dataset config
from detectron2.data.datasets import register_coco_instances

register_coco_instances("my_dataset", "path/to/json", "path/to/image_root")

dataloader.train = L(build_detection_train_loader)(
    dataset=L(get_detection_dataset_dicts)(names="my_dataset"),
    ...
```

**Comment by rentainhe** [comment]
Please refer to [custom.py](https://github.com/IDEA-Research/detrex/blob/main/configs/common/data/custom.py) to see how to register and use coco-like datasets in detrex and d2!

**Comment by ma3252788** [comment]
> Here is an example:
> 
> ```python
> # dataset config
> from detectron2.data.datasets import register_coco_instances
> 
> register_coco_instances("my_dataset", {}, "path/to/json", "path/to/image_root") 
> 
> dataloader.train = L(build_detection_train_loader)(
>     dataset=L(get_detection_dataset_dicts)(names="my_dataset"),
>     ...
> ```

I see. Thank you very much for your reply.

**Comment by rentainhe** [comment]
> > Here is an example:
> > ```python
> > # dataset config
> > from detectron2.data.datasets import register_coco_instances
> > 
> > register_coco_instances("my_dataset", {}, "path/to/json", "path/to/image_root") 
> > 
> > dataloader.train = L(build_detection_train_loader)(
> >     dataset=L(get_detection_dataset_dicts)(names="my_dataset"),
> >     ...
> > ```
> 
> I see. Thank you very much for your reply.

You're welcome~

**Comment by sjtu-cz** [comment]
File "/workspace/detrex/detectron2/detectron2/evaluation/coco_evaluation.py", line 240, in _eval_predictions
    assert category_id < num_classes, (
AssertionError: A prediction has class=14, but the dataset only has 11 classes and predicted class id should be in [0, 10].

**Comment by FrostbiteLee** [comment]
> File "/workspace/detrex/detectron2/detectron2/evaluation/coco_evaluation.py", line 240, in _eval_predictions assert category_id < num_classes, ( AssertionError: A prediction has class=14, but the dataset only has 11 classes and predicted class id should be in [0, 10].
> 
> I use a custom dataset for training, but meet the error.

I had the same problem. I need help.

**Comment by xiaolizai** [comment]
> File "/workspace/detrex/detectron2/detectron2/evaluation/coco_evaluation.py", line 240, in _eval_predictions assert category_id < num_classes, ( AssertionError: A prediction has class=14, but the dataset only has 11 classes and predicted class id should be in [0, 10].
> 
> I use a custom dataset for training, but meet the error.

Maybe can help you. https://github.com/IDEA-Research/detrex/issues/267#issuecomment-1637273202

**Comment by sjtu-cz** [comment]
您好，你的邮件我已经收到~

**Comment by wwzstudy** [comment]
After modifying the custom.py file, run python tools/train_net.py --config-file projects/dab_detr/configs/models/dab_detr_r50.py, A Missing key train error occurred
full_key: train
object_type=dict

**Comment by wwzstudy** [comment]
ERROR [09/30 16:04:15 d2.config.instantiate]: Error when instantiating detectron2.data.build.build_detection_train_loader!
