### ISSUE TITLE
Train Dino with focalNet backbone on custom datasets

### ISSUE THREAD

**Issue by 4BD0U** [IDEA-Research/detrex#189]
I am having difficulty training a Dino model with a FocalNet backbone on a custom dataset. Although I was able to successfully train the model using a SWIN-L backbone, after 10 epochs with FocalNet, all detection scores are still below 1%. I am unable to understand why this might be the case as the dataset used is identical and the pre-trained model provided in the GitHub repository was used as a starting point. Can you help me understand what might be causing this issue, please?

**Comment by rentainhe** [comment]
> I am having difficulty training a Dino model with a FocalNet backbone on a custom dataset. Although I was able to successfully train the model using a SWIN-L backbone, after 10 epochs with FocalNet, all detection scores are still below 1%. I am unable to understand why this might be the case as the dataset used is identical and the pre-trained model provided in the GitHub repository was used as a starting point. Can you help me understand what might be causing this issue, please?

Does this phenomenon occur very often or just a random experiments？

**Comment by rentainhe** [comment]
Actually, this error is relatively difficult to locate, and it requires more experiments to observe. If it's convenient, could you provide more information about the custom dataset you're using ?

**Comment by 4BD0U** [comment]
Sorry, it was just an error. My issue was with the Dino repository, not this one. The pre-trained model provided was intended for Dino 5scale with focalNet, but the configuration file corresponded to Dino 4scale.
