### ISSUE TITLE
Using Albumentations for more advanced transforms

### ISSUE THREAD

**Issue by fernandorovai** [IDEA-Research/detrex#206]
Had anyone added albumentations to apply rotation and other different transforms on the dataloader?
Any idea on what should be the easiest way to implement that? Since detrex uses lazy configs, I don't know if has an easy way to add this feature.

**Comment by rentainhe** [comment]
> Had anyone added albumentations to apply rotation and other different transforms on the dataloader? Any idea on what should be the easiest way to implement that? Since detrex uses lazy configs, I don't know if has an easy way to add this feature.

Maybe you can refer to d2's documentation for more details about the augmentation used in detectron2~ and lazyconfig is just a single wrap of the augmentation module, all you need to do is implement your specific augmentation and wrap it with LazyCall in LazyConfig~ @fernandorovai
