### ISSUE TITLE
Provide more checkpoints.

### ISSUE THREAD

**Issue by YiqunChen1999** [IDEA-Research/detrex#207]
Hi, thanks for your great project.

Do you have plans to convert checkpoints (e.g., DAB-DETR-R50-DC5) from other repos of IDEA-Research?

Thanks.

**Comment by rentainhe** [comment]
> Hi, thanks for your great project.
> 
> Do you have plans to convert checkpoints (e.g., DAB-DETR-R50-DC5) from other repos of IDEA-Research?
> 
> Thanks.

Sure, if you need this checkpoint, we would like to convert it and add it into detrex model zoo

**Comment by rentainhe** [comment]
> Hi, thanks for your great project.
> 
> Do you have plans to convert checkpoints (e.g., DAB-DETR-R50-DC5) from other repos of IDEA-Research?
> 
> Thanks.

We've provided the checkpoint converter to convert the weights from original repo, you can also check this documentation for mode details: https://detrex.readthedocs.io/en/latest/tutorials/Converters.html

**Comment by YiqunChen1999** [comment]
> > Hi, thanks for your great project.
> > Do you have plans to convert checkpoints (e.g., DAB-DETR-R50-DC5) from other repos of IDEA-Research?
> > Thanks.
> 
> Sure, if you need this checkpoint, we would like to convert it and add it into detrex model zoo @YiqunChen1999

Sure, I have tried to convert DAB-DETR-R50-DC5, but the converted model only gives 4.35 AP. It would be helpful if you provide this checkpoint. 

BTW, it would save much time for the community if it's possible to provide other checkpoints. 

Thank you!

**Comment by rentainhe** [comment]
> > > Hi, thanks for your great project.
> > > Do you have plans to convert checkpoints (e.g., DAB-DETR-R50-DC5) from other repos of IDEA-Research?
> > > Thanks.
> > 
> > 
> > Sure, if you need this checkpoint, we would like to convert it and add it into detrex model zoo @YiqunChen1999
> 
> Sure, I have tried to convert DAB-DETR-R50-DC5, but the converted model only gives 4.35 AP. It would be helpful if you provide this checkpoint.
> 
> BTW, it would save much time for the community if it's possible to provide other checkpoints.
> 
> Thank you!

OK, we will try to convert it for the community

**Comment by alrightkami** [comment]
It would be helpful as well to have a MaskDINO with [Swin](https://github.com/IDEA-Research/detrex/tree/main/projects/maskdino#:~:text=To-,Release,-These%20models%20can) backbones.

**Comment by rentainhe** [comment]
> It would be helpful as well to have a MaskDINO with [Swin](https://github.com/IDEA-Research/detrex/tree/main/projects/maskdino#:~:text=To-,Release,-These%20models%20can) backbones.

Sure, we will refine MaskDINO project recently, and the checkpoint convert will be finished in this PR: https://github.com/IDEA-Research/detrex/pull/208 @alrightkami @YiqunChen1999

**Comment by rentainhe** [comment]
> > > Hi, thanks for your great project.
> > > Do you have plans to convert checkpoints (e.g., DAB-DETR-R50-DC5) from other repos of IDEA-Research?
> > > Thanks.
> > 
> > 
> > Sure, if you need this checkpoint, we would like to convert it and add it into detrex model zoo @YiqunChen1999
> 
> Sure, I have tried to convert DAB-DETR-R50-DC5, but the converted model only gives 4.35 AP. It would be helpful if you provide this checkpoint.
> 
> BTW, it would save much time for the community if it's possible to provide other checkpoints.
> 
> Thank you!

The temperature in position embedding should set to 10 in DAB-DETR-R50-DC5

**Comment by rentainhe** [comment]
I'm closing this issue~ feel free to reopen it if needed
