### ISSUE TITLE
[New Feature] Slurm training script

### ISSUE THREAD

**Issue by rayleizhu** [IDEA-Research/detrex#213]
How can I start training on a slurm cluster? Do I need to take care of ddp initialization routines by myself?

**Comment by FengLi-ust** [comment]
Yes, you can refer to [DINO slurm scripts](https://github.com/IDEA-Research/DINO/blob/main/run_with_submitit.py) as an example. We will upload this script in the future.

**Comment by rayleizhu** [comment]
I’ve implemented slurm launcher using submitit. It supports:

one-line lunch command on slurm cluster, just like existing trainer provided by current detrex.
automatic experiments name generation according to hyper-parameter overrides.
automatically requeue and resume from latest checkpoint when a running job is preempted or reaches maximum execution time.

Are you interested to merge my implementation to detrex? If yes, I will create a pull request by the end of this week.

**Comment by rayleizhu** [comment]
I’ve implemented slurm launcher using submitit. It supports:

* one-line lunch command on slurm cluster, just like existing trainer provided by current detrex.
* automatic experiments name generation according to hyper-parameter overrides.
* automatically requeue and resume from latest checkpoint when a running job is preempted or reaches maximum execution time.

Are you interested to merge my implementation to detrex? If yes, I will create a pull request by the end of this week.

**Comment by FengLi-ust** [comment]
Of course, that would be great!

**Comment by rentainhe** [comment]
Thanks for your contribution, we will close this issue~ reopen this at anytime if you need more help~
