### ISSUE TITLE
Wrong lr schedule if batch size changes?

### ISSUE THREAD

**Issue by rayleizhu** [IDEA-Research/detrex#214]
It seems that detrex currently has only IterBasedRunner implemented, and assumes a constant batch size of 16, right? As a result, If I change the batch size (for example, 16 -> 64 for more efficient training on GPUs with larger memory, such as V100 or A100), the lr schedule will be wrong, right?

**Comment by rentainhe** [comment]
> It seems that detrex currently has only IterBasedRunner implemented, and assumes a constant batch size of 16, right? As a result, If I change the batch size (for example, 16 -> 64 for more efficient training on GPUs with larger memory, such as V100 or A100), the lr schedule will be wrong, right?

Yes, you should change the scheduler at the same time~ we will try to modify this part in detrex in next version

**Comment by rentainhe** [comment]
I'm closing this issue~ feel free to reopen it if needed~
