### ISSUE TITLE
About visualization on dino

### ISSUE THREAD

**Issue by WesleyZCheng** [IDEA-Research/detrex#221]
Hi, I noticed that we have a file that visualizes the data from the json file. Through the code, we can see that this is the json inference data generated during training, and it is not the data I want to get during inference. What should I do if I want to visualize images or videos in real-time by running model inference?

**Comment by rentainhe** [comment]
> Hi, I noticed that we have a file that visualizes the data from the json file. Through the code, we can see that this is the json inference data generated during training, and it is not the data I want to get during inference. What should I do if I want to visualize images or videos in real-time by running model inference?

detrex has already provided several visualization ways to visualize data:
- To **visualize training training datas**: you can follow this documentation to visualize your training datas: [docs on visualize training datas](https://detrex.readthedocs.io/en/latest/tutorials/Tools.html#visualize-datasets)
- To **visualize the inference json results**: please follow this tutorial: [docs on visualize inference results](https://detrex.readthedocs.io/en/latest/tutorials/Tools.html#visualize-predictions)
- To **visualize your own demo image or videos**: please follow this tutorial: [docs on visualize your own demo with pretrained weights](https://detrex.readthedocs.io/en/latest/tutorials/Getting_Started.html#inference-demo-with-pre-trained-models)

**Comment by WesleyZCheng** [comment]
> > Hi, I noticed that we have a file that visualizes the data from the json file. Through the code, we can see that this is the json inference data generated during training, and it is not the data I want to get during inference. What should I do if I want to visualize images or videos in real-time by running model inference?
> 
> detrex has already provided several visualization ways to visualize data:
> 
> * To **visualize training training datas**: you can follow this documentation to visualize your training datas: [docs on visualize training datas](https://detrex.readthedocs.io/en/latest/tutorials/Tools.html#visualize-datasets)
> * To **visualize the inference json results**: please follow this tutorial: [docs on visualize inference results](https://detrex.readthedocs.io/en/latest/tutorials/Tools.html#visualize-predictions)
> * To **visualize your own demo image or videos**: please follow this tutorial: [docs on visualize your own demo with pretrained weights](https://detrex.readthedocs.io/en/latest/tutorials/Getting_Started.html#inference-demo-with-pre-trained-models)
> 
> Maybe you can follow **the third way** to solve your problem I guess, using the [demo](https://github.com/IDEA-Research/detrex/tree/main/demo) in detrex to visualize your demo image or video.

Thanks! I found it in the latest code you release, my code was downloaded 3 months ago, and i do not update my code in time.

**Comment by rentainhe** [comment]
> > > Hi, I noticed that we have a file that visualizes the data from the json file. Through the code, we can see that this is the json inference data generated during training, and it is not the data I want to get during inference. What should I do if I want to visualize images or videos in real-time by running model inference?
> > 
> > 
> > detrex has already provided several visualization ways to visualize data:
> > 
> > * To **visualize training training datas**: you can follow this documentation to visualize your training datas: [docs on visualize training datas](https://detrex.readthedocs.io/en/latest/tutorials/Tools.html#visualize-datasets)
> > * To **visualize the inference json results**: please follow this tutorial: [docs on visualize inference results](https://detrex.readthedocs.io/en/latest/tutorials/Tools.html#visualize-predictions)
> > * To **visualize your own demo image or videos**: please follow this tutorial: [docs on visualize your own demo with pretrained weights](https://detrex.readthedocs.io/en/latest/tutorials/Getting_Started.html#inference-demo-with-pre-trained-models)
> > 
> > Maybe you can follow **the third way** to solve your problem I guess, using the [demo](https://github.com/IDEA-Research/detrex/tree/main/demo) in detrex to visualize your demo image or video.
> 
> Thanks! I found it in the latest code you release, my code was downloaded 3 months ago, and i do not update my code in time.

You're welcome~
