### ISSUE TITLE
Problem in CDN implementation in DINO code

### ISSUE THREAD

**Issue by Artificial-Inability** [IDEA-Research/detrex#225]
Although part of the CDN implementation is not completely correct, it doesn't hurt the performance. I have done experiments to confirm that CDN module is better than DN module. Thanks for your great work and you can close this issue.
![image](https://user-images.githubusercontent.com/102346323/225549632-cf203ddf-5b04-4a8e-9ca9-06152cbd95bb.png)

**Comment by HaoZhang534** [comment]
@Artificial-Inability The negative boxes are not designed to be outside the original boxes. Their noises only need to be larger than positive ones.

**Comment by Artificial-Inability** [comment]
> @Artificial-Inability The negative boxes are not designed to be outside the original boxes. Their noises only need to be larger than positive ones.

Your answer didn't resolve the problem in my example. The negative box [left+0.75w, top+0.75h, right-0.75w, bottom-0.75h] in my example is not larger than the largest positive boxes. 

I draw a picture for the mechanism in the code:
![image](https://user-images.githubusercontent.com/102346323/224622626-cc72377b-1350-4c43-9093-da9b7772ef40.png)

The transformation in the code is moving the red circle point(top left point of the green gt box) into a point inside one of the red square and the blue circle point(bottom right point) into one of the blue square. The resulting box is not guaranteed to be "larger than positive ones"

Moreover, I didn't find any word in the paper or the code in this repo support your understanding about "negative noises only need to be larger than positive ones.". @rentainhe can you assign this issue to the author of DINO to confirm this? Thanks!

**Comment by Artificial-Inability** [comment]
> @Artificial-Inability The negative boxes are not designed to be outside the original boxes. Their noises only need to be larger than positive ones.

Your answer didn't resolve the problem in my example. The negative box [left+0.75w, top+0.75h, right-0.75w, bottom-0.75h] in my example is not larger than the largest positive boxes. 

I draw a picture for the mechanism in the code:
![image](https://user-images.githubusercontent.com/102346323/224622626-cc72377b-1350-4c43-9093-da9b7772ef40.png)

The transformation in the code is moving the red circle point(top left point of the green gt box) into a point inside one of the red square and the blue circle point(bottom right point) into one of the blue square. The resulting box is not guaranteed to be "larger than positive ones"

Moreover, I didn't find any word in the paper or the code in this repo support your understanding about "negative noises only need to be larger than positive ones.". @rentainhe can you assign this issue to the author of DINO to confirm this? Thanks!
