### ISSUE TITLE
Is checkpointing supported / should it be added?

### ISSUE THREAD

**Issue by FabianSchuetze** [IDEA-Research/detrex#228]
Thanks for the wonderful repo - it's a pleasure to work with it and to read the code. 

Is checkpointing currently supported by detrex?  If not, would there be an interest in a PR that adds checkpointing? I have added it for the Dino encoder and decoder and it seemed to work well.

**Comment by rentainhe** [comment]
> Thanks for the wonderful repo - it's a pleasure to work with it and to read the code.
> 
> Is checkpointing currently supported by detrex? If not, would there be an interest in a PR that adds checkpointing? I have added it for the Dino encoder and decoder and it seemed to work well.

Sure, we appreciate any kind of contribution from the community~ You can open a pull request about this, thank you so much~

**Comment by rentainhe** [comment]
BTW, we simply support checkpointing in DINO before, but a little bit not that elegant, we will highly appreciate your pull request about it~

**Comment by FabianSchuetze** [comment]
I just saw the new release and PR #200 . The solution is very elegant and useful. Thanks a lot!
