### ISSUE TITLE
How to modify training config from launch command?

### ISSUE THREAD

**Issue by yxchng** [IDEA-Research/detrex#233]
Is it possible to do command like this `python tools/train_net.py --config-file projects/deformable_detr/configs/path/to/config.py --num-gpus 8 --output_dir 'example'`? Or must I change the config file?

**Comment by rentainhe** [comment]
> Is it possible to do command like this `python tools/train_net.py --config-file projects/deformable_detr/configs/path/to/config.py --num-gpus 8 --output_dir 'example'`? Or must I change the config file?

You can modify training config in command line as:

```bash
python tools/train_net.py --config-file projects/deformable_detr/configs/path/to/config.py --num-gpus 8 train.output_dir="/path/to/output_dir/"
```

**Comment by rentainhe** [comment]
Note that you can modify any config at command line using detrex, only one thing to care is, you should match the namespace in command line and your own config file:

```bash
python tools/train_net.py --config-file config.py --num-gpus 8 train.output_dir="./" train.max_iters=90000 ...
```

**Comment by rentainhe** [comment]
I'm closing this issue~ Feel free to reopen it if needed~
