### ISSUE TITLE
help,could you install the detectron2 with cuda 11.3?

### ISSUE THREAD

**Issue by CasonTsai** [IDEA-Research/detrex#246]
hello ,i have met a fault below when i use this comand 'python -m pip install -e detectron2' to install detectron2

The detected CUDA version (11.3) mismatches the version that was used to compile PyTorch (10.2). Please make sure to use the same CUDA versions.
![image](https://user-images.githubusercontent.com/18262642/229262059-51b8b51c-adde-4e0f-91c7-75f9b5f9a68e.png)

my cuda version is 11.3 which is recommended

**Comment by CasonTsai** [comment]
pytorch version is 1.12

**Comment by rentainhe** [comment]
It seems you should update your pytorch version, you should install the version complied with cuda11.3 in pytorch official website

**Comment by CasonTsai** [comment]
i have fixed it ,the reason is that when install torch with pip should down the torch which is pre-builded with the same cuda version
