### ISSUE TITLE
Any plans on supporting rotated bounding box detectors

### ISSUE THREAD

**Issue by ogencoglu** [IDEA-Research/detrex#257]
Any plans on supporting rotated bounding box detectors on top of axis-aligned bounding boxes that it provides?

**Comment by rentainhe** [comment]
Hello @ogencoglu , our repo aims to hold most of the detr algorithms, if there are some rotated bounding box algorithms we will like to implement them, but not that hurry

**Comment by rentainhe** [comment]
We've noticed that there has been some paper works about rotated box detection using DETR like DINO: https://arxiv.org/pdf/2305.07598.pdf

It will be nice if they released their code and pre-trained weights, you can keep an eye on this work, and I'm going to close this issue now, feel free to reopen it if necessary.

Rotated box may not that hurry in our future release, as there are not much DETR-like works on it
