### ISSUE TITLE
Where is the 63.3ap model reported in the paper? 

### ISSUE THREAD

**Issue by amanikiruga** [IDEA-Research/detrex#260]
Thank you for your work! I was wondering where I can find the model checkpoint trained on Objects365 reported in the paper which had 63.3 ap on COCO?
I can only see the following: 
<img width="930" alt="image" src="https://user-images.githubusercontent.com/69642575/234274154-5a152b1a-cbc4-47ba-bb41-92a1b27d2af3.png">
None of them have 63.3 AP. 
Best regards

**Comment by rentainhe** [comment]
> Thank you for your work! I was wondering where I can find the model checkpoint trained on Objects365 reported in the paper which had 63.3 ap on COCO? I can only see the following: <img alt="image" width="930" src="https://user-images.githubusercontent.com/69642575/234274154-5a152b1a-cbc4-47ba-bb41-92a1b27d2af3.png"> None of them have 63.3 AP. Best regards

Sry, we did not release this checkpoint in detrex, you can find the checkpoint with better performance in [FocalNet-DINO](https://github.com/FocalNet/FocalNet-DINO)

**Comment by amanikiruga** [comment]
thank you!!
