### ISSUE TITLE
path config

### ISSUE THREAD

**Issue by Zesheng666** [IDEA-Research/detrex#265]
Which file in the DINO code is used to configure the path of the COCO dataset? I've been searching for a while but couldn't find it.

**Comment by rentainhe** [comment]
> Which file in the DINO code is used to configure the path of the COCO dataset? I've been searching for a while but couldn't find it.

We defined it here: 
- the config file: https://github.com/IDEA-Research/detrex/blob/main/configs/common/data/coco_detr.py
- the dataset: https://github.com/IDEA-Research/detrex/blob/main/detrex/data/detr_dataset_mapper.py

**Comment by Zesheng666** [comment]
非常感谢解答，有几个细节问题想向你请教：VX:yzs1721770653。感激不尽！










杨泽生



南方科技大学/学生/研究生/2022级研究生



广东省深圳市南山区学苑大道1088号




&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Wed, May 24, 2023 00:49 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [IDEA-Research/detrex] path config (Issue #265)

&nbsp;



  
出现 No such file or directory: 'datasets/coco/annotations/instances_train2017.json'，在哪个文件里面修改数据集的相关的路径呢？上面那两个文件里面似乎没有
  
你需要指定一下
 export DETECTRON2_DATASETS=/path/to/datasets
 
即可
 
如果你需要修改这个路径的话，需要修改你安装下来的d2文件夹的dataset/builtin.py，具体文件路径在:
 
https://github.com/facebookresearch/detectron2/blob/2c6c380f94a27bd8455a39506c9105f652b9f760/detectron2/data/datasets/builtin.py#L35
