### ISSUE TITLE
Could you add the Co-DETR model in the future?

### ISSUE THREAD

**Issue by hotcore** [IDEA-Research/detrex#277]
Could you add the Co-DETR model in the future? the link:https://github.com/Sense-X/Co-DETR.
I'm looking forward to this lol.

**Comment by rentainhe** [comment]
> Could you add the Co-DETR model in the future? the link:https://github.com/Sense-X/Co-DETR. I'm looking forward to this lol.

Sure, we will add Co-DETR and RT-DETR to our future release plan, please stay tuned!

**Comment by hotcore** [comment]
bravo!!

**Comment by rentainhe** [comment]
> bravo!!

But it may take some times for this, cuz Co-DETR was implemented based on MMDet and RT-DETR was based on Paddle, it may take some time to transfer them to detrex codebase

**Comment by hotcore** [comment]
> > bravo!!
> 
> But it may take some times for this, cuz Co-DETR was implemented based on MMDet and RT-DETR was based on Paddle, it may take some time to transfer them to detrex codebase

sure,  I'm graduating next year, and I hope to see it before I graduate 😂.
Anyway, it's a great project, definitely!!
