### ISSUE TITLE
Wandb init

### ISSUE THREAD

**Issue by ShenghaiRong** [IDEA-Research/detrex#301]
When enable wandb, it encounters an error from the following line:
https://github.com/IDEA-Research/detrex/blob/b42b0e1c7b47a4d32f2fd18d0b6dced41a8ab8a5/detrex/utils/events.py#L38.
It seems that the initialization of wandb does not support DictConfig. After modifying the above line to :
`config=OmegaConf.to_container(cfg, resolve=True),`
it works.

**Comment by rentainhe** [comment]
Thank you so much for reporting this issue, I was wondering what's the `OmegaConf` version in your environment, would you like to propose a new pull request for fixing this : ) ?

**Comment by ShenghaiRong** [comment]
The OmegaConf version in my environment is 2.1.0. 
Ok, I will PR for this.
