### ISSUE TITLE
About finetuning a DINO model you provided on my custom dataset

### ISSUE THREAD

**Issue by Kim-yhao** [IDEA-Research/detrex#306]
I want to finetune a DINO with swin-b you provided in Model Zoo on my custom dataset, but it shows that the number of categories does not match. 
![3932ffe3038a43467f62ea4bec757a3](https://github.com/IDEA-Research/detrex/assets/103106751/de8a610d-893c-4c1d-8287-5623645e7f5d)
I guess this is because I didn't change the number of categories. Can you tell me where to change it? Or are there some parameters I need to ignore when loading the model? Where to change them if I need to? **THX!**

**Comment by rentainhe** [comment]
> I want to finetune a DINO with swin-b you provided in Model Zoo on my custom dataset, but it shows that the number of categories does not match. ![3932ffe3038a43467f62ea4bec757a3](https://user-images.githubusercontent.com/103106751/267027576-de8a610d-893c-4c1d-8287-5623645e7f5d.png) I guess this is because I didn't change the number of categories. Can you tell me where to change it? Or are there some parameters I need to ignore when loading the model? Where to change them if I need to? **THX!**

You should check your config and modify the classes num in the config file

**Comment by Kim-yhao** [comment]
> 

I add model.num_classes to the config. It works. THX!

**Comment by hdmjdp** [comment]
How to finetue on custom dataset using the pretrained ckpt? where is the script?
