### ISSUE TITLE
Adding pre-trained models

### ISSUE THREAD

**Issue by Claraeunice** [IDEA-Research/detrex#324]
Hi, where can I add a pre-trained model? I've been looking for a long time but couldn't find

Also, I would like to ask when using detrex to train visdrone dataset, should I change the configuration in detrex or in detectron2?

**Comment by rentainhe** [comment]
> Hi, where can I add a pre-trained model? I've been looking for a long time but couldn't find
> 
> Also, I would like to ask when using detrex to train visdrone dataset, should I change the configuration in detrex or in detectron2?

Hello, we put our pre-trained weights here: [detrex-storage](https://github.com/IDEA-Research/detrex-storage), and if you like to add your own weights to detrex, you can try to put it on github and share the link with us, we will mention it on our project or documentation

If you want to train on your own dataset, you need to update the dataset config and some model config like `num_classes`  (default to 80), if your dataset is larger than 80-classes

**Comment by Claraeunice** [comment]
> > 嗨，我在哪里可以添加预训练模型？我一直在寻找很长时间，但找不到
> > 另外，我想问一下，当使用 detrex 训练 visdrone 数据集时，我应该更改 detrex 还是 detectron2 中的配置？
> 
> 您好，我们把预训练的权重放在这里：detrex-storage，如果你想在[detrex](https://github.com/IDEA-Research/detrex-storage)中添加自己的权重，可以尝试放在github上，分享链接给我们，我们会在我们的项目或文档中提及
> 
> 如果要在自己的数据集上进行训练，则需要更新数据集配置和一些模型配置，例如（默认为 80），如果数据集大于 80 个类`num_classes`


Thanks for the quick reply!

The thing is, I need to train the visdrone dataset (10 classes) using detr-dc5, but I'm having some trouble:

1.I can't find which configuration files I should change, because there's detrex in there as well as detectron2, and the two files look very similar.For example, I obviously modified the configuration batch_size of detr-dc5 in detrex, but the output from executing the training instruction is still the value before the modification, and I really don't know how to go about it.

2.I tried to change the config dataset path and category last night and it works but I'm not sure if it's the right one, I noticed that there doesn't seem to be a prompt in there for the current epochs?

Your help is greatly appreciated.

**Comment by Claraeunice** [comment]
> > Hi, where can I add a pre-trained model? I've been looking for a long time but couldn't find
> > Also, I would like to ask when using detrex to train visdrone dataset, should I change the configuration in detrex or in detectron2?
> 
> Hello, we put our pre-trained weights here: [detrex-storage](https://github.com/IDEA-Research/detrex-storage), and if you like to add your own weights to detrex, you can try to put it on github and share the link with us, we will mention it on our project or documentation
> 
> If you want to train on your own dataset, you need to update the dataset config and some model config like `num_classes` (default to 80), if your dataset is larger than 80-classes



> > Hi, where can I add a pre-trained model? I've been looking for a long time but couldn't find
> > Also, I would like to ask when using detrex to train visdrone dataset, should I change the configuration in detrex or in detectron2?
> 
> Hello, we put our pre-trained weights here: [detrex-storage](https://github.com/IDEA-Research/detrex-storage), and if you like to add your own weights to detrex, you can try to put it on github and share the link with us, we will mention it on our project or documentation
> 
> If you want to train on your own dataset, you need to update the dataset config and some model config like `num_classes` (default to 80), if your dataset is larger than 80-classes

I just visited your homepage and found your IP in shenzhen, can we speak Chinese?
