### ISSUE TITLE
关于mixed_selection的问题

### ISSUE THREAD

**Issue by nhw649** [IDEA-Research/detrex#331]
作者你好，h_deformable_detr中使用的mixed_selection是哪篇文章提出的呢？是Conditional DETR for Fast Training Convergence这篇的idea还是一个提点的trick呢？

**Comment by nhw649** [comment]
```
if not self.mixed_selection:
    query_pos, query = torch.split(pos_trans_out, c, dim=2)
else:
    # query_pos here is the content embed for deformable DETR
    query = query_embed.unsqueeze(0).expand(bs, -1, -1)
    query_pos, _ = torch.split(pos_trans_out, c, dim=2)
```

**Comment by rentainhe** [comment]
是DINO这篇工作里提到的一个涨点技巧，可以参考一下:
- DINO arXiv: https://arxiv.org/abs/2203.03605
- DINO project in detrex: https://github.com/IDEA-Research/detrex/tree/main/projects/dino

**Comment by nhw649** [comment]
> 是DINO这篇工作里提到的一个涨点技巧，可以参考一下:
> 
> * DINO arXiv: https://arxiv.org/abs/2203.03605
> * DINO project in detrex: https://github.com/IDEA-Research/detrex/tree/main/projects/dino

好的，谢谢。
