### ISSUE TITLE
RuntimeError: Undefined backend is not a valid device type

### ISSUE THREAD

**Issue by bozihu** [IDEA-Research/detrex#93]
During the installation, no error occurs. When I use the model containing ms_deform_attn to test the code, the losses.backward() will occur the following error. 

Traceback (most recent call last):
  File "/DATA1/code/detrex/detectron2/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/DATA1/code/detrex/tools/train_net_debug.py", line 115, in run_step
    losses.backward()
  File "/home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
  File "/home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages/torch/autograd/function.py", line 199, in apply
    return user_fn(self, *args)
  File "/home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages/torch/autograd/function.py", line 340, in wrapper
    outputs = fn(ctx, *args)
  File "/DATA1/code/detrex/detrex/layers/multi_scale_deform_attn.py", line 83, in backward
    grad_value, grad_sampling_loc, grad_attn_weight = _C.ms_deform_attn_backward(
RuntimeError: Undefined backend is not a valid device type
python-BaseException

Process finished with exit code -1

**Comment by rentainhe** [comment]
> 

@bozihu Would you like to share more info about your python environments and the building process like https://github.com/IDEA-Research/detrex/issues/85

And you can check if `CUDA_HOME` is None in `setup.py`, if `CUDA_HOME` is None, there's no errors when building detrex, but the `detrex._C` module can not be built correctly

After the above checking, you can try to rebuild detrex again follows https://github.com/IDEA-Research/detrex/issues/85#issuecomment-1261827235

**Comment by bozihu** [comment]
This is my python environments
# Name                    Version                   Build  Channel
absl-py                   1.2.0                     <pip>
addict                    2.4.0                     <pip>
antlr4-python3-runtime    4.8                       <pip>
attrs                     22.1.0                    <pip>
autoflake                 1.7.0                     <pip>
black                     22.3.0                    <pip>
ca-certificates           2022.07.19           h06a4308_0
cachetools                5.2.0                     <pip>
certifi                   2022.9.24        py38h06a4308_0
charset-normalizer        2.1.1                     <pip>
click                     8.1.3                     <pip>
cloudpickle               2.2.0                     <pip>
contourpy                 1.0.5                     <pip>
cycler                    0.11.0                    <pip>
detectron2                0.6                       <pip>
detrex                    0.1.0                     <pip>
fairscale                 0.4.12                    <pip>
filelock                  3.8.0                     <pip>
flake8                    3.8.1                     <pip>
fonttools                 4.37.4                    <pip>
future                    0.18.2                    <pip>
fvcore                    0.1.5.post20220512           <pip>
google-auth               2.12.0                    <pip>
google-auth-oauthlib      0.4.6                     <pip>
grpcio                    1.49.1                    <pip>
huggingface-hub           0.10.0                    <pip>
hydra-core                1.1.2                     <pip>
idna                      3.4                       <pip>
importlib-metadata        5.0.0                     <pip>
importlib-resources       5.2.3                     <pip>
iniconfig                 1.1.1                     <pip>
iopath                    0.1.9                     <pip>
isort                     4.3.21                    <pip>
kiwisolver                1.4.4                     <pip>
ld_impl_linux-64          2.38                 h1181459_1
libffi                    3.3                  he6710b0_2
libgcc-ng                 11.2.0               h1234567_1
libstdcxx-ng              11.2.0               h1234567_1
Markdown                  3.4.1                     <pip>
MarkupSafe                2.1.1                     <pip>
matplotlib                3.6.1                     <pip>
mccabe                    0.6.1                     <pip>
mmcv-full                 1.6.2                     <pip>
mypy-extensions           0.4.3                     <pip>
ncurses                   6.3                  h5eee18b_3
numpy                     1.22.4                    <pip>
oauthlib                  3.2.1                     <pip>
omegaconf                 2.1.0                     <pip>
opencv-python             4.6.0.66                  <pip>
openssl                   1.1.1q               h7f8727e_0
packaging                 21.3                      <pip>
pathspec                  0.10.1                    <pip>
Pillow                    9.2.0                     <pip>
pip                       22.2.2           py38h06a4308_0
platformdirs              2.5.2                     <pip>
pluggy                    1.0.0                     <pip>
portalocker               2.5.1                     <pip>
protobuf                  3.19.6                    <pip>
psutil                    5.9.2                     <pip>
py                        1.11.0                    <pip>
pyasn1                    0.4.8                     <pip>
pyasn1-modules            0.2.8                     <pip>
pybind11                  2.10.0                    <pip>
pycocotools               2.0.5                     <pip>
pycodestyle               2.6.0                     <pip>
pydot                     1.4.2                     <pip>
pyflakes                  2.2.0                     <pip>
pyparsing                 3.0.9                     <pip>
pytest                    7.1.3                     <pip>
python                    3.8.13               h12debd9_0
python-dateutil           2.8.2                     <pip>
PyYAML                    6.0                       <pip>
readline                  8.1.2                h7f8727e_1
requests                  2.28.1                    <pip>
requests-oauthlib         1.3.1                     <pip>
rsa                       4.9                       <pip>
scipy                     1.7.3                     <pip>
setuptools                59.5.0                    <pip>
setuptools                63.4.1           py38h06a4308_0
six                       1.16.0                    <pip>
sqlite                    3.39.3               h5082296_0
tabulate                  0.9.0                     <pip>
tensorboard               2.10.1                    <pip>
tensorboard-data-server   0.6.1                     <pip>
tensorboard-plugin-wit    1.8.1                     <pip>
termcolor                 2.0.1                     <pip>
timm                      0.6.11                    <pip>
tk                        8.6.12               h1ccaba5_0
tomli                     2.0.1                     <pip>
torch                     1.10.1+cu111              <pip>
torchaudio                0.10.1+rocm4.1            <pip>
torchvision               0.11.2+cu111              <pip>
tqdm                      4.64.1                    <pip>
typing_extensions         4.4.0                     <pip>
urllib3                   1.26.12                   <pip>
Werkzeug                  2.2.2                     <pip>
wheel                     0.37.1             pyhd3eb1b0_0
xz                        5.2.6                h5eee18b_0
yacs                      0.1.8                     <pip>
yapf                      0.32.0                    <pip>
zipp                      3.9.0                     <pip>
zlib                      1.2.12               h5eee18b_3

**Comment by bozihu** [comment]
This is my install log for build an editable version of detrex. 
pip install -e .
Obtaining file:///DATA1/code/detrex
  Preparing metadata (setup.py) ... done
Requirement already satisfied: cloudpickle in /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages (from detrex==0.1.0) (2.2.0)
Requirement already satisfied: hydra-core in /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages (from detrex==0.1.0) (1.2.0)
Collecting omegaconf==2.1.0
  Downloading omegaconf-2.1.0-py3-none-any.whl (74 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.5/74.5 kB 553.6 kB/s eta 0:00:00
Collecting pybind11
  Downloading pybind11-2.10.0-py3-none-any.whl (213 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 213.3/213.3 kB 1.7 MB/s eta 0:00:00
Collecting flake8==3.8.1
  Downloading flake8-3.8.1-py2.py3-none-any.whl (72 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 3.9 MB/s eta 0:00:00
Collecting isort==4.3.21
  Using cached isort-4.3.21-py2.py3-none-any.whl (42 kB)
Requirement already satisfied: black==22.3.0 in /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages (from detrex==0.1.0) (22.3.0)
Collecting autoflake
  Downloading autoflake-1.7.0-py2.py3-none-any.whl (17 kB)
Requirement already satisfied: timm in /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages (from detrex==0.1.0) (0.6.11)
Collecting pytest
  Downloading pytest-7.1.3-py3-none-any.whl (298 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.2/298.2 kB 2.6 MB/s eta 0:00:00
Collecting scipy==1.7.3
  Using cached scipy-1.7.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (39.3 MB)
Collecting psutil
  Downloading psutil-5.9.2-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (284 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 284.8/284.8 kB 2.3 MB/s eta 0:00:00
Collecting opencv-python
  Using cached opencv_python-4.6.0.66-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (60.9 MB)
Requirement already satisfied: tomli>=1.1.0 in /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages (from black==22.3.0->detrex==0.1.0) (2.0.1)
Requirement already satisfied: click>=8.0.0 in /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages (from black==22.3.0->detrex==0.1.0) (8.1.3)
Requirement already satisfied: pathspec>=0.9.0 in /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages (from black==22.3.0->detrex==0.1.0) (0.10.1)
Requirement already satisfied: mypy-extensions>=0.4.3 in /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages (from black==22.3.0->detrex==0.1.0) (0.4.3)
Requirement already satisfied: platformdirs>=2 in /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages (from black==22.3.0->detrex==0.1.0) (2.5.2)
Requirement already satisfied: typing-extensions>=3.10.0.0 in /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages (from black==22.3.0->detrex==0.1.0) (4.4.0)
Collecting mccabe<0.7.0,>=0.6.0
  Using cached mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting pyflakes<2.3.0,>=2.2.0
  Downloading pyflakes-2.2.0-py2.py3-none-any.whl (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.0/67.0 kB 279.3 kB/s eta 0:00:00
Collecting pycodestyle<2.7.0,>=2.6.0a1
  Downloading pycodestyle-2.6.0-py2.py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.4/41.4 kB 1.2 MB/s eta 0:00:00
Requirement already satisfied: PyYAML>=5.1.* in /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages (from omegaconf==2.1.0->detrex==0.1.0) (6.0)
Collecting antlr4-python3-runtime==4.8
  Using cached antlr4_python3_runtime-4.8-py3-none-any.whl
Collecting numpy<1.23.0,>=1.16.5
  Downloading numpy-1.22.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.9/16.9 MB 7.4 MB/s eta 0:00:00
Requirement already satisfied: packaging in /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages (from hydra-core->detrex==0.1.0) (21.3)
Requirement already satisfied: importlib-resources in /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages (from hydra-core->detrex==0.1.0) (5.10.0)
Collecting hydra-core
  Downloading hydra_core-1.1.2-py3-none-any.whl (147 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.4/147.4 kB 7.1 MB/s eta 0:00:00
Collecting importlib-resources<5.3
  Downloading importlib_resources-5.2.3-py3-none-any.whl (27 kB)
Collecting iniconfig
  Using cached iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting attrs>=19.2.0
  Downloading attrs-22.1.0-py2.py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 6.0 MB/s eta 0:00:00
Collecting pluggy<2.0,>=0.12
  Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/py/
Collecting py>=1.8.2
  Using cached py-1.11.0-py2.py3-none-any.whl (98 kB)
Requirement already satisfied: huggingface-hub in /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages (from timm->detrex==0.1.0) (0.10.0)
Requirement already satisfied: torch>=1.7 in /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages (from timm->detrex==0.1.0) (1.10.1+cu111)
Requirement already satisfied: torchvision in /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages (from timm->detrex==0.1.0) (0.11.2+cu111)
Requirement already satisfied: zipp>=3.1.0 in /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages (from importlib-resources<5.3->hydra-core->detrex==0.1.0) (3.9.0)
Requirement already satisfied: filelock in /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages (from huggingface-hub->timm->detrex==0.1.0) (3.8.0)
Requirement already satisfied: requests in /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages (from huggingface-hub->timm->detrex==0.1.0) (2.28.1)
Requirement already satisfied: tqdm in /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages (from huggingface-hub->timm->detrex==0.1.0) (4.64.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages (from packaging->hydra-core->detrex==0.1.0) (3.0.9)
Requirement already satisfied: pillow!=8.3.0,>=5.3.0 in /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages (from torchvision->timm->detrex==0.1.0) (9.2.0)
Requirement already satisfied: idna<4,>=2.5 in /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages (from requests->huggingface-hub->timm->detrex==0.1.0) (3.4)
Requirement already satisfied: charset-normalizer<3,>=2 in /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages (from requests->huggingface-hub->timm->detrex==0.1.0) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages (from requests->huggingface-hub->timm->detrex==0.1.0) (2022.9.24)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages (from requests->huggingface-hub->timm->detrex==0.1.0) (1.26.12)
Installing collected packages: mccabe, iniconfig, antlr4-python3-runtime, pyflakes, pycodestyle, pybind11, py, psutil, pluggy, omegaconf, numpy, isort, importlib-resources, attrs, scipy, pytest, opencv-python, hydra-core, flake8, autoflake, detrex
  Attempting uninstall: antlr4-python3-runtime
    Found existing installation: antlr4-python3-runtime 4.9.3
    Uninstalling antlr4-python3-runtime-4.9.3:
      Successfully uninstalled antlr4-python3-runtime-4.9.3
  Attempting uninstall: omegaconf
    Found existing installation: omegaconf 2.2.3
    Uninstalling omegaconf-2.2.3:
      Successfully uninstalled omegaconf-2.2.3
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.3
    Uninstalling numpy-1.23.3:
      Successfully uninstalled numpy-1.23.3
  Attempting uninstall: importlib-resources
    Found existing installation: importlib-resources 5.10.0
    Uninstalling importlib-resources-5.10.0:
      Successfully uninstalled importlib-resources-5.10.0
  Attempting uninstall: hydra-core
    Found existing installation: hydra-core 1.2.0
    Uninstalling hydra-core-1.2.0:
      Successfully uninstalled hydra-core-1.2.0
  Running setup.py develop for detrex
Successfully installed antlr4-python3-runtime-4.8 attrs-22.1.0 autoflake-1.7.0 detrex-0.1.0 flake8-3.8.1 hydra-core-1.1.2 importlib-resources-5.2.3 iniconfig-1.1.1 isort-4.3.21 mccabe-0.6.1 numpy-1.22.4 omegaconf-2.1.0 opencv-python-4.6.0.66 pluggy-1.0.0 psutil-5.9.2 py-1.11.0 pybind11-2.10.0 pycodestyle-2.6.0 pyflakes-2.2.0 pytest-7.1.3 scipy-1.7.3

**Comment by bozihu** [comment]
If there is no MultiScaleDeformableAttention, the model will run correctly.

**Comment by bozihu** [comment]
Thanks for your reply, and I CUDA_HOME is not None!:

>>> from torch.utils.cpp_extension import CUDA_HOME
>>> print(CUDA_HOME)
/usr/local/cuda

**Comment by rentainhe** [comment]
> If there is no MultiScaleDeformableAttention, the model will run correctly.

After checking the `CUDA_HOME` and rebuilding the detrex, you can quickly test the MultiScaleAttention module by running:
```python
python tests/test_ms_deform_attn.py
```

**Comment by bozihu** [comment]
Thanks for your reply! When I check CUDA_HOME, it is /usr/local/cuda. I don't konw whether it is right.

>>> from torch.utils.cpp_extension import CUDA_HOME
>>> print(CUDA_HOME)
/usr/local/cuda

And I test the MultiScaleDeformableAttention module by running:

pytest tests/test_ms_deform_attn.py

here is the log:

=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.8.13, pytest-7.1.3, pluggy-1.0.0
rootdir: /DATA1/hzb/code/detrex
plugins: hydra-core-1.1.2
collected 2 items

tests/test_ms_deform_attn.py ..                                                                                                                                     [100%]

============================================================================ warnings summary =============================================================================
../../../../home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages/torchvision/transforms/functional_pil.py:228
  /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages/torchvision/transforms/functional_pil.py:228: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
    interpolation: int = Image.BILINEAR,

../../../../home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages/torchvision/transforms/functional_pil.py:296
  /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages/torchvision/transforms/functional_pil.py:296: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
    interpolation: int = Image.NEAREST,

../../../../home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages/torchvision/transforms/functional_pil.py:312
  /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages/torchvision/transforms/functional_pil.py:312: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
    interpolation: int = Image.NEAREST,

../../../../home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages/torchvision/transforms/functional_pil.py:329
  /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages/torchvision/transforms/functional_pil.py:329: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
    interpolation: int = Image.BICUBIC,

detectron2/detectron2/data/transforms/transform.py:46
  /DATA1/hzb/code/detrex/detectron2/detectron2/data/transforms/transform.py:46: DeprecationWarning: LINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
    def __init__(self, src_rect, output_size, interp=Image.LINEAR, fill=0):

detectron2/detectron2/data/transforms/augmentation_impl.py:112
  /DATA1/hzb/code/detrex/detectron2/detectron2/data/transforms/augmentation_impl.py:112: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
    def __init__(self, shape, interp=Image.BILINEAR):

detectron2/detectron2/data/transforms/augmentation_impl.py:139
  /DATA1/hzb/code/detrex/detectron2/detectron2/data/transforms/augmentation_impl.py:139: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
    self, short_edge_length, max_size=sys.maxsize, sample_style="range", interp=Image.BILINEAR

detectron2/detectron2/data/transforms/augmentation_impl.py:213
  /DATA1/hzb/code/detrex/detectron2/detectron2/data/transforms/augmentation_impl.py:213: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
    interp: int = Image.BILINEAR,

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
===================================================================== 2 passed, 8 warnings in 22.07s ======================================================================

**Comment by rentainhe** [comment]
> Thanks for your reply! When I check CUDA_HOME, it is /usr/local/cuda. I don't konw whether it is right.
> 
> > > > from torch.utils.cpp_extension import CUDA_HOME
> > > > print(CUDA_HOME)
> > > > /usr/local/cuda
> 
> And I test the MultiScaleDeformableAttention module by running:
> 
> pytest tests/test_ms_deform_attn.py
> 
> here is the log:
> 
> =========================================================================== test session starts =========================================================================== platform linux -- Python 3.8.13, pytest-7.1.3, pluggy-1.0.0 rootdir: /DATA1/code/detrex plugins: hydra-core-1.1.2 collected 2 items
> 
> tests/test_ms_deform_attn.py .. [100%]
> 
> ============================================================================ warnings summary ============================================================================= ../../../../home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages/torchvision/transforms/functional_pil.py:228 /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages/torchvision/transforms/functional_pil.py:228: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. interpolation: int = Image.BILINEAR,
> 
> ../../../../home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages/torchvision/transforms/functional_pil.py:296 /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages/torchvision/transforms/functional_pil.py:296: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead. interpolation: int = Image.NEAREST,
> 
> ../../../../home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages/torchvision/transforms/functional_pil.py:312 /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages/torchvision/transforms/functional_pil.py:312: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead. interpolation: int = Image.NEAREST,
> 
> ../../../../home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages/torchvision/transforms/functional_pil.py:329 /home/ubuntu/anaconda3/envs/detrex/lib/python3.8/site-packages/torchvision/transforms/functional_pil.py:329: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead. interpolation: int = Image.BICUBIC,
> 
> detectron2/detectron2/data/transforms/transform.py:46 /DATA1/hzb/code/detrex/detectron2/detectron2/data/transforms/transform.py:46: DeprecationWarning: LINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. def **init**(self, src_rect, output_size, interp=Image.LINEAR, fill=0):
> 
> detectron2/detectron2/data/transforms/augmentation_impl.py:112 /DATA1/hzb/code/detrex/detectron2/detectron2/data/transforms/augmentation_impl.py:112: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. def **init**(self, shape, interp=Image.BILINEAR):
> 
> detectron2/detectron2/data/transforms/augmentation_impl.py:139 /DATA1/hzb/code/detrex/detectron2/detectron2/data/transforms/augmentation_impl.py:139: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. self, short_edge_length, max_size=sys.maxsize, sample_style="range", interp=Image.BILINEAR
> 
> detectron2/detectron2/data/transforms/augmentation_impl.py:213 /DATA1/hzb/code/detrex/detectron2/detectron2/data/transforms/augmentation_impl.py:213: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. interp: int = Image.BILINEAR,
> 
> -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html ===================================================================== 2 passed, 8 warnings in 22.07s ======================================================================

I thinks `CUDA_HOME=/usr/local/cuda` is right ! See this reply~ https://github.com/IDEA-Research/detrex/issues/85#issuecomment-1263006332

If this test can be passed correctly, I thinks there's no bugs in `MultiScaleDeformableAttention` now, you can try to test the models with this module again.

**Comment by bozihu** [comment]
I find when I use pycharm in debug mode, the error will occur. And if I use it in terminal, there is no bug occurs.

**Comment by rentainhe** [comment]
> I find when I use pycharm in debug mode, the error will occur. And if I use it in terminal, there is no bug occurs.

Oh, maybe something went wrong in pycharm debug mode, using terminal is a better choice I guess~
