### ISSUE TITLE
Can famous data augment methods such as Mixup and Mosaic improve performance?

### ISSUE THREAD

**Issue by VCBE123** [IDEA-Research/detrex#96]

**Comment by SlongLiu** [comment]
Thanks for the question. 
We have tried some strong augmentations like cropping and rotating for DINO, but showed no obvious improvements. Other models are trained under the same augs as DETR.
It is a good topic to explore the impacts of mixup and mosaic, but we have not explored them.

**Comment by rentainhe** [comment]
I think maybe we can move this topic to [detrex Discussions](https://github.com/IDEA-Research/detrex/discussions) to see if others have some experiences on it ? It's a good topic I think.

**Comment by rentainhe** [comment]
As there is no more activity, I am closing the issue~ Feel free to reopen it if necessary. Or you can leave a new issue if you meet some other problems.
