### ISSUE TITLE
RuntimeError: common/data/coco_detr.py not available in detrex configs

### ISSUE THREAD

**Issue by NSMBGhost** [IDEA-Research/detrex#97]
hello，I meet this problem when training customer data

**Comment by rentainhe** [comment]
> hello，I meet this problem when training customer data

hello, please make sure you've installed detrex correctly~, after installing detrex, the config in `configs/common` will be linked to `detrex/config/configs`, therefore you can use the interface `detrex.config.get_config("common/data/coco_detr.py")` in projects

**Comment by NSMBGhost** [comment]
> > hello，I meet this problem when training customer data
> 
> @NSMBGhost hello, please make sure you've **installed detrex correctly**. After installing detrex, the configs under `configs/common` will be soft linked to `detrex/config/configs`, therefore, you can use the interface `detrex.config.get_config("common/data/coco_detr.py")` in projects.

I have intalled detrex according to the tutorials and runed these command correctly
$ git clone https://github.com/IDEA-Research/detrex.git
$ cd detrex
$ git submodule init
$ git submodule update
$ python -m pip install -e detectron2
$ pip install -e .
and the directory is the following picture:
![image](https://user-images.githubusercontent.com/50392713/195809784-b26514af-8547-4e7d-8398-1672787c7965.png)
but still not solve the problem,do I miss something?

**Comment by rentainhe** [comment]
> > > hello，I meet this problem when training customer data
> > 
> > 
> > @NSMBGhost hello, please make sure you've **installed detrex correctly**. After installing detrex, the configs under `configs/common` will be soft linked to `detrex/config/configs`, therefore, you can use the interface `detrex.config.get_config("common/data/coco_detr.py")` in projects.
> 
> I have intalled detrex according to the tutorials and runed these command correctly $ git clone https://github.com/IDEA-Research/detrex.git $ cd detrex $ git submodule init $ git submodule update $ python -m pip install -e detectron2 $ pip install -e . and the directory is the following picture: ![image](https://user-images.githubusercontent.com/50392713/195809784-b26514af-8547-4e7d-8398-1672787c7965.png) but still not solve the problem,do I miss something?

Please check the directory `detrex/config` to see if there is and dir named `detrex/config/configs`. It will look like:
![image](https://user-images.githubusercontent.com/48727989/195829258-d3b3f67e-0107-42d4-a104-05207e54796d.png)

And after building detrex, there will be the `dir` named `build`, but I didn't see it in your directory.
![image](https://user-images.githubusercontent.com/48727989/195829618-32df15fa-99fd-48f7-8a8b-19e25b945788.png)

**Comment by rentainhe** [comment]
> 

Seems like the build process is right~, maybe you can check if you are using right environment.

**Comment by NSMBGhost** [comment]
> > > > hello，I meet this problem when training customer data
> > > 
> > > 
> > > @NSMBGhost hello, please make sure you've **installed detrex correctly**. After installing detrex, the configs under `configs/common` will be soft linked to `detrex/config/configs`, therefore, you can use the interface `detrex.config.get_config("common/data/coco_detr.py")` in projects.
> > 
> > 
> > I have intalled detrex according to the tutorials and runed these command correctly $ git clone https://github.com/IDEA-Research/detrex.git $ cd detrex $ git submodule init $ git submodule update $ python -m pip install -e detectron2 $ pip install -e . and the directory is the following picture: ![image](https://user-images.githubusercontent.com/50392713/195809784-b26514af-8547-4e7d-8398-1672787c7965.png) but still not solve the problem,do I miss something?
> 
> Please check the directory `detrex/config` to see if there is and dir named `detrex/config/configs`. It will look like: ![image](https://user-images.githubusercontent.com/48727989/195829258-d3b3f67e-0107-42d4-a104-05207e54796d.png)
> 
> And after building detrex, there will be the `dir` named `build`, but I didn't see it in your directory. ![image](https://user-images.githubusercontent.com/48727989/195829618-32df15fa-99fd-48f7-8a8b-19e25b945788.png)

When I use pycharm to debug this project, I will report an error. But today I used vscode, and it has miraculously run successfully. Now I want to train myself with coco type custom data, but I encounter difficulties. There are only four types of data sets. It seems that detectron2 does not support putting custom data sets directly in the coco dataset directory. How can I modify the code to run successfully

**Comment by rentainhe** [comment]
> 

Yes, seems like using pycharm debug mode will meet some strange bugs here. Actually you can try to use your own dataset by hacking the [train_net.py](https://github.com/IDEA-Research/detrex/blob/f42868091282171c3f2e438a61be9cfc36d9e631/tools/train_net.py#L49), you can pass your own dataloader here.

And you can also follow the [detectron2 custom dataset tutorials](https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html) to see how to register your own datasets into the dataset directory

**Comment by NSMBGhost** [comment]
> 
thanks a lot！

**Comment by rentainhe** [comment]
As there is no more activity, I am closing the issue~ Feel free to reopen it if necessary.
