### ISSUE TITLE
ImportError: Cannot import 'detrex._C', therefore 'MultiScaleDeformableAttention' is not available.

### ISSUE THREAD

**Issue by Sjyhne** [IDEA-Research/detrex#98]
Hello!

I'm following the installation guide, but facing issues when trying to run models with MultiScaleDeformableAttention. As the title states, I'm receiving the following error:

```ImportError: Cannot import 'detrex._C', therefore 'MultiScaleDeformableAttention' is not available.```

Relevant packages from conda list:

detectron2              0.6                    dev_0                                           <develop>
detrex                     0.1.0                 dev_0                                           <develop>
pytorch                   1.10.1               py3.7_cuda10.2_cudnn7.6.5_0    pytorch
pytorch-mutex        1.0                    cuda                                              pytorch
torchaudio              0.10.1               py37_cu102                                  pytorch
torchvision              0.11.2               py37_cu102                                  pytorch

1. Clean conda environment with python version 3.7
2. Install pytorch according to the PyTorch installation guides.
3. Clone detrex
4. Init and update submodules
5. python -m pip install -e detectron2
6. pip install -e .

However when running:

``` python tools/train_net.py --config-file projects/dino/configs/dino_r50_4scale_12ep.py ```

I get the error above.

Is there any known solutions for this issue?

**Comment by rentainhe** [comment]
> Hello!
> 
> I'm following the installation guide, but facing issues when trying to run models with MultiScaleDeformableAttention. As the title states, I'm receiving the following error:
> 
> `ImportError: Cannot import 'detrex._C', therefore 'MultiScaleDeformableAttention' is not available.`
> 
> Relevant packages from conda list:
> 
> detectron2 0.6 dev_0 detrex 0.1.0 dev_0 pytorch 1.10.1 py3.7_cuda10.2_cudnn7.6.5_0 pytorch pytorch-mutex 1.0 cuda pytorch torchaudio 0.10.1 py37_cu102 pytorch torchvision 0.11.2 py37_cu102 pytorch
> 
> 1. Clean conda environment with python version 3.7
> 2. Install pytorch according to the PyTorch installation guides.
> 3. Clone detrex
> 4. Init and update submodules
> 5. python -m pip install -e detectron2
> 6. pip install -e .
> 
> However when running:
> 
> `python tools/train_net.py --config-file projects/dino/configs/dino_r50_4scale_12ep.py`
> 
> I get the error above.
> 
> Is there any known solutions for this issue?

You can also follow this issue to see if it can help you to fix the installation problem. https://github.com/IDEA-Research/detrex/issues/85#issuecomment-1263006332

**Comment by Sjyhne** [comment]
Yeah, thanks! This might be my issue. However, I am not able to access the CUDA_HOME, as cuda is not installed locally on the server I'm training on. Are there any other possible solutions to the issue? Circumventing the CUDA_HOME?

**Comment by rentainhe** [comment]
> Yeah, thanks! This might be my issue. However, I am not able to access the CUDA_HOME, as cuda is not installed locally on the server I'm training on. Are there any other possible solutions to the issue? Circumventing the CUDA_HOME?

Maybe you can try to build detrex on that server~

**Comment by rentainhe** [comment]
As there is no more activity, I am closing the issue~ Feel free to reopen it if necessary. Or you can leave a new issue if you meet some other problems.
